# NodePort

# A NodePort service is the most primitive way to get external traffic directly to your service. NodePort, as the name implies, opens a specific port on all the Nodes (the VMs), and any traffic that is sent to this port is forwarded to the service.

# Exposes the Service on each Node's IP at a static port (the NodePort). A ClusterIP Service, to which the NodePort Service routes, is automatically created. You'll be able to contact the NodePort Service, from outside the cluster, by requesting <NodeIP>:<NodePort>.

apiVersion: v1
kind: Service

metadata:
  name: my-nodeport-service

spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - name: http
      port: 80 # Port number exposed internally in cluster
      targetPort: 80 # The port that the container is listening on
      nodePort: 30036 # Access this service via this port number
      protocol: TCP
