apiVersion: v1
kind: Pod
metadata:
  name: kubectl
  namespace: default

spec:
  serviceAccount: test-sa
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "20000"]
    # command: ["sh", "-c", "while true; do sleep 3600; done"]