apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods

subjects:
- kind: User
  name: harsh
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: pods-reader
  apiGroup: rbac.authorization.k8s.io