apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods

subjects:
- kind: User
  name: harsh
  apiGroup: rbac.authorization.k8s.io

- kind: ServiceAccount
  name: test-sa # Attaching the role to service account.

roleRef:
  kind: Role
  name: pods-reader
  apiGroup: rbac.authorization.k8s.io