name: PR Feedback # Runs on every PR and posts a comment with the results.

on: pull_request

jobs:
  feedback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: npm test

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const body = '✅ All tests passed!';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
