{
 "title": "MinIO Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } },
   { "name": "buckets", "query": { "query": "label_values(bucket)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Server, Drive, Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tenant Capacity",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\"$scrape_jobs\"}) by (job)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (job))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (job)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Drive Health",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_system_drive_health{job=~\"tenant-0-system\"} * 50",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_cluster_usage_total_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Online Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_nodes_online_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Buckets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minio_cluster_bucket_total{job=~\"$scrape_jobs\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Objects per Bucket",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(minio_bucket_usage_object_total{bucket=~\"$buckets\"}) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_objects_size_distribution{job=~\"$scrape_jobs\"} != 0",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Object Version Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_objects_version_distribution{job=~\"$scrape_jobs\"} != 0",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Drives",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_drive_online_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "ONLINE"
    },
    {
     "expr": "max(minio_cluster_drive_offline_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "OFFLINE"
    }
   ]
  },
  {
   "title": "Read, Write I/O",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar"
    }
   ]
  },
  {
   "title": "Health Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_erasure_set_online_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Online Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_read_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Read Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_write_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Write Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_healing_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Healing Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Status"
    }
   ]
  },
  {
   "title": "Syscalls",
   "type": "timeseries",
   "description": "Number of online drives per MinIO Server",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{job}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{job}}]"
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 API Ingress Rate ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"}[$__rate_interval]))",
       "legendFormat": "Data Received [{{job}}]"
      }
     ]
    },
    {
     "title": "S3 API Egress Rate ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"}[$__rate_interval]))",
       "legendFormat": "Data Sent [{{job}}]"
      }
     ]
    },
    {
     "title": "S3 API Request Error Rate (4xx)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 13, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (api) (increase(minio_s3_requests_4xx_errors_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
       "legendFormat": "/{{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Error Rate (5xx)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_5xx_errors_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
       "legendFormat": "{{server,api}}"
      }
     ]
    },
    {
     "title": "Total S3 Ingress",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "S3 API Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (api) (increase(minio_s3_requests_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
       "legendFormat": "/{{api}}"
      }
     ]
    },
    {
     "title": "Total S3 Egress",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Scanning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Since Last Scan",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(minio_usage_last_activity_nano_seconds{job=~\"$scrape_jobs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scanned Objects in Tenant",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 3, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minio_node_scanner_objects_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scanned Directories",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minio_node_scanner_directories_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scanned Versions in Tenant",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minio_node_scanner_versions_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bucket Scans Started",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minio_node_scanner_bucket_scans_started{job=~\"$scrape_jobs\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Bucket Scans Finished",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minio_node_scanner_bucket_scans_finished{job=~\"$scrape_jobs\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}