apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync # The name of the secret to be created inside cluster
  data: # data hold in above named secret
    - secretKey: username-sec # Keyname on which the fetched value is stored
      remoteRef:
        key: kv-v2/data/vault-demo/user-pass # Absolute secret path of vault
        property: username # key inside a remote secret
    - secretKey: password-sec
      remoteRef:
        key: kv-v2/data/vault-demo/user-pass
        property: password