apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: argo-cluster-workflow-template-container
  namespace: argo
spec:
  templates:
    - name: container-template
      container:
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["echo 'Cluster workflow template message'"]