apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-dag-wf-
  namespace: argo
spec:
  entrypoint: dag-template
  templates:
    - name: dag-template
      dag:
        tasks:
          - name: A
            templateRef:
              name: argo-workflow-template-container
              template: container-template
          - name: B
            template: script-template
            dependencies: [A]
          - name: C
            template: resource-template
            arguments:
              parameters:
                - name: rand_num_input
                  value: "{{tasks.B.outputs.parameters.rand_num_output}}"
            dependencies: [A, B]
          - name: D
            template: suspend-template
            dependencies: [A, B, C]
    - name: container-template
      container:
        image: alpine
        command:
          - "/bin/sh"
          - "-c"
        args: ["echo 'Hello from container'"]
    - name: script-template
      outputs:
        parameters:
          - name: rand_num_output
            # value: "20"
            valueFrom:
              path: "/tmp/rand_num"
      script:
        image: python:alpine3.6
        command:
          - python
        source: | # Script to execute
          import random
          i = random.randint(1, 10)

          with open('/tmp/rand_num', 'w') as f:
            f.write(str(i))
            print("Written", i, "into file: /tmp/rand_num")
    - name: resource-template
      inputs:
        parameters:
          - name: rand_num_input
      resource:
        action: create # can be: get, create, apply, delete, replace, patch
        manifest: |    # Configmap is created in the same namespace the workflow runs
          apiVersion: v1
          kind: ConfigMap
          metadata:
            generateName: argo-wf-configmap-
            labels:
              created_by: argo-workflows
            namespace: default
          data:
            author: HarshPanchal
            randomNumber: "{{inputs.parameters.rand_num_input}}"
    - name: suspend-template
      suspend:
        duration: "10s"
  ttlStrategy:
    secondsAfterCompletion: 120 # TTL for completed jobs
    secondsAfterFailure: 180    # TTL for failed jobs
    secondsAfterSuccess: 120    # TTL for succeed jobs