apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka

metadata:
  name: kafka-data
  namespace: kafka

spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}

  kafka:
    config:
      auto.create.topics.enable: true # Enable auto topic creation
      inter.broker.protocol.version: '3.9' # Use the same version as the Kafka cluster
      log.message.format.version: '3.9'
      offsets.topic.replication.factor: 1 # Set to 1 for single-node clusters
      ssl.cipher.suites: >- # Use strong cipher suites
        TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_AES_256_GCM_SHA384
      ssl.enabled.protocols: 'TLSv1.3, TLSv1.2'
      ssl.protocol: TLSv1.3
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1 # Set to 1 for single-node clusters
      default.replication.factor: 3 # Set default replication factor to 3 for high availability
      min.insync.replicas: 2 # Set minimum in-sync replicas to 2 for higher availability
      offsets.topic.num.partitions: 3 # Set to 3 for better performance

    jvmOptions: # JVM options for Kafka. Adjust memory settings to 8GB
      '-Xms': 8192m # Initial heap size
      '-Xmx': 8192m # Maximum heap size

    listeners:
      - authentication:
          type: scram-sha-512
        name: tlsinternal
        port: 9095
        tls: true
        type: internal # Internal listener with TLS
      - authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 30960
          brokers:
            - advertisedHost: 192.168.26.25
              broker: 0
              nodePort: 30961
        name: tlsexternal
        port: 9096
        tls: true
        type: nodeport
      - name: plain
        port: 9092
        tls: false
        type: internal
      - configuration:
          bootstrap:
            nodePort: 30940
          brokers:
            - advertisedHost: 192.168.26.25
              broker: 0
              nodePort: 30921
        name: external
        port: 9094
        tls: false
        type: nodeport

    replicas: 3

    storage:
      type: jbod # Use JBOD storage for Kafka
      volumes:
        - class: sc-kafka
          deleteClaim: false # Do not delete PVC on Kafka deletion
          id: 0
          size: 5Gi
          type: persistent-claim

    template:
      kafkaContainer:
        securityContext:
          privileged: true # Allow privileged mode for Kafka container
      pod:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        securityContext:
          runAsGroup: 0 # Run as root group
          runAsUser: 0 # Run as root user

    version: 3.9.0

  kafkaExporter:
    groupRegex: .* # Export all groups
    template:
      pod:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
    topicRegex: .* # Export all topics

  zookeeper:
    replicas: 3
    storage:
      class: sc-zookeeper
      deleteClaim: false
      size: 5Gi
      type: persistent-claim
    template:
      pod:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
