apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance

metadata:
  name: kafka-rebalance-goals
  labels:
    strimzi.io/cluster: kafka-data-connect-cluster

spec:
  goals:
    - CpuCapacityGoal
    - NetworkInboundCapacityGoal
    - DiskCapacityGoal
    - RackAwareGoal
    - MinTopicLeadersPerBrokerGoal
    - NetworkOutboundCapacityGoal
    - ReplicaCapacityGoal
  skipHardGoalCheck: true
  mode: full