apiVersion: monitoring.coreos.com/v1
kind: Prometheus

metadata:
  annotations:
    meta.helm.sh/release-name: prom-graf
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prom-graf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 73.2.2
    chart: kube-prometheus-stack-73.2.2
    heritage: Helm
    release: prom-graf
  name: prom-graf-kube-prometheus-prometheus
  namespace: monitoring
  resourceVersion: "578247"
  uid: 3b0aba45-9530-43c7-b3bc-aa412cd5d1e2

spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - prometheus
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - prom-graf-kube-prometheus-prometheus
          topologyKey: kubernetes.io/hostname
        weight: 100

  alerting:
    alertmanagers:
    - apiVersion: v2
      name: prom-graf-kube-prometheus-alertmanager
      namespace: monitoring
      pathPrefix: /
      port: http-web

  automountServiceAccountToken: true
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: http://prom-graf-kube-prometheus-prometheus.monitoring:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v3.4.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false

  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      app: strimzi

  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prom-graf

  replicas: 1
  retention: 10d
  routePrefix: /

  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: prom-graf

  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector: {}
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  serviceAccountName: prom-graf-kube-prometheus-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}

  shards: 1
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v3.4.1
  walCompression: true
