apiVersion: v1
kind: Service

metadata:
  labels:
    app.kubernetes.io/instance: kafka-data
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka-exporter
    app.kubernetes.io/part-of: strimzi-kafka-data
    name: kafka-exporter
    strimzi.io/cluster: kafka-data
    strimzi.io/component-type: kafka-exporter
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-data-kafka-exporter

  name: kafka-metrics
  namespace: myproject

spec:
  type: NodePort
  ports:
  - nodePort: 32682
    port: 9404
    protocol: TCP
    targetPort: 9404

  selector:
    app.kubernetes.io/instance: kafka-data
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka-exporter
    app.kubernetes.io/part-of: strimzi-kafka-data
    name: kafka-exporter
    strimzi.io/cluster: kafka-data
    strimzi.io/component-type: kafka-exporter
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-data-kafka-exporter
