apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment

metadata:
  name: example-runnerdeploy
  namespace: github-runner

spec:
  replicas: 1
  template:
    spec:
      repository: HarshPanchal18/HarshPanchal18
