apiVersion: apps/v1
kind: Deployment

metadata:
  name: minio-mc
  labels:
    app: minio-client

spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-client

  template:
    metadata:
      labels:
        app: minio-client

    spec:
      containers:
        - name: mc
          image: minio/mc:RELEASE.2025-05-21T01-59-54Z
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              sleep infinity # Sleeps forever so you can still exec into the pod
          #     echo "MinIO is up. Creating alias..." &&
          #     until mc alias set $MINIO_TENANT $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY; do
          #       echo "Failed to create alias. Retrying..."; sleep 2;
          #     done &&
          #     echo "Alias created. Pod is now sleeping..." &&
          #     sleep infinity # Sleeps forever so you can still exec into the pod
          # env:
          #   - name: MINIO_TENANT
          #     value: myminio
          #   - name: MINIO_URL
          #     value: https://minio.demo.svc.cluster.local # Replace with your MinIO service URL
          #   - name: MINIO_ACCESS_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: test-tenant-user-0
          #         key: CONSOLE_ACCESS_KEY
          #   - name: MINIO_SECRET_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: test-tenant-user-0
          #         key: CONSOLE_SECRET_KEY
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: minio-upload-data
              mountPath: /data/minio-uploads  # Mount path inside the container
      restartPolicy: Always
      volumes:
        - name: minio-upload-data
          persistentVolumeClaim:
            claimName: minio-upload-pvc
