apiVersion: v1
kind: Pod
metadata:
  name: ambassador-pattern-example
spec:
  containers:
    - name: myapp
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            echo "Calling external service via ambassador...";
            wget -qO- http://172.20.0.3:30004;
            sleep 10;
          done
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: ambassador
      image: alpine/socat
      args:
        - tcp-listen:30004,fork
        - tcp-connect:jsonplaceholder.typicode.com:443
      command: ["socat"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"