apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-minio-mirroring
  name: minio-cleanup-bucket-pod
  namespace: ns-minio
spec:
  containers:
    - command:
        - /bin/sh
        - '-c'
        - >
          mkdir -p /root/.mc && cat /root/mc-config/config.json >
          /root/.mc/config.json && mc rm --recursive --force temp-tenant/buckert-0 &
          mc rm --recursive --force temp-tenant/buckert-0 &
          mc rm --recursive --force temp-tenant/buckert-0 &
          sleep 2;
      image: minio/mc
      name: pod-minio-mirroring
      volumeMounts:
        - mountPath: /root/mc-config/
          name: config-volume
      resources:
        limits:
          cpu: '0.5'
          memory: 512Mi
        requests:
          cpu: '0.1'
          memory: 256Mi
  volumes:
    - configMap:
        name: mc-config-minio
      name: config-volume