apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-2
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    namespace: "dev" # Deploy applications in "dev" namespace only
    server: "*"
  sourceRepos:
    - "*"