apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: default
spec:
  encryptedData:
    secret.json: AgBlVIh6S2XqSdMh999GQEKkg+3/DkB4XXroKTzts7wRBjqQAc9WfHUcTF9k2MiFpJ2/yJKCKy14a59aOpTO8kjatEYPef3q27BynfP9fYXp6XobKK9OyRwS4uEpQLrCZbLPV2M2t/mpAW1M3M6+76cv1BCUb04qRU84y+UbQLsYpCMlErEMoVjiGA2e1jEZqNOFK9gJgGNEoxEdPaeGvzG5S3b16uhTFORdBjxDtEns/Ey42RgkzxS79o5kPmJLv4IAfM/ZVa8JffMvt2jkwmIgygfKnP5GdnhXneGM25yfBDTOXV6vcJrtf1Aggmw+IXxzQ9xglhuajxvC2SugFhcNnbCxb0QW2dlQt8PIyrhPQgdfXDngR8ExhUjMm5ZvOv7JOvkAdgVWP1CPmLbCW76rmk4DBu5+u81HSnMh67nyPVJNpu/JdSH1NhYydiaEG3ETE0aNWrSsvgWRshXld1GBW7nhlre0jkW9yWoPiik44yQDG3YNke9BiDUfuO5k7Q45jV0EU+d/xP+6ZXkDOGROPxE62xjAVuyA/50v5PHJGztAT8nGaYYb1rzu8toklMfyBxlX39NPy6vnInWEST4hek+4iYyb3/ShfeUHBqvB3QtDRzSshOLUF9ppSbs23M0jERf/fwe836XlvmE2WaUwh4kwZm/8dw6EbOBJaF2Up2cr5ePKSVqDz/irzJds35Fi13cQFEzAThYx2ueY0yBIo8mPSg1O/QvGgyYu
  template:
    metadata:
      name: mysecret
      namespace: default
    type: Opaque