apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  secret.json: |-
    {
      "apikey": "db-api-key"
    }

# kubectl create secret generic mysecret --from-file secret.yaml