apiVersion: batch/v1
kind: Job

metadata:
  name: mongo-backup

spec:
  backOffLimit: 5
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 60 # The job will be deleted after 1 minute of completion.

  template:
    spec:
      containers:
        - name: mongo-backup
          image: mongo
          command: ["/bin/sh", "-c"]
          args: [ # Mongodump is a utility for creating backups of MongoDB databases in binary format.
            'mongodump --uri "mongodb://user1:${MONGO_PASSWORD}@mongo-0.mongo.default.svc.cluster.local:27017,mongo" -o /usr/share/mongodump-$(date + "%d%m%Y-%H%M%S")'
          ]
          volumeMounts:
            - mountPath: /usr/share/mongodump
              name: mongodump-volume
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password

      volumes:
        - name: mongodump-volume
          persistentVolumeClaim:
            claimName: mongodump-pvc # The PVC must be created before the job is run.
      restartPolicy: Never # The pods won't be restarted if they fail.