apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard

provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

### Registry PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv

spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/harsh/volume/registry

  storageClassName: standard

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: harbor

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

### JobService PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobservice-pv

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/harsh/volume/jobservice

  storageClassName: standard

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobservice-pvc
  namespace: harbor

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

### Database PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/harsh/volume/database

  storageClassName: standard

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: harbor

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

### Redis PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/harsh/volume/redis

  storageClassName: standard

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: harbor

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

### Trivy PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-pv

spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/harsh/volume/trivy

  storageClassName: standard

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-pvc
  namespace: harbor

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard