apiVersion: v1
kind: Pod

metadata:
  name: pvc-pod

spec:
  containers:
  - name: my-cont
    image: nginx
    volumeMounts:
      - mountPath: /pers-storage
        name: my-storage

  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: pvc-example