apiVersion: v1
kind: Pod

metadata:
  name: env-pod

spec:
  containers:
    - name: secret-test
      image: nginx
      command: ['sh', '-C', 'echo "Username: $USER" "Password: $PASSWORD"']

      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user.txt

        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: pass.txt