apiVersion: v1
kind: Pod

metadata:
  name: my-pod

spec:
  containers:
  - name: my-cont1
    image: nginx
    volumeMounts:
    - mountPath: /cache
      name: cache-volume

  - name: my-cont2
    image: alpine
    volumeMounts:
    - mountPath: /cache # Any files written in /cache in either container are shared between them.
      name: cache-volume

  volumes:
  - name: cache-volume
    emptyDir: {} # The data in an emptyDir volume is deleted once the pod is removed.