apiVersion: v1
kind: PersistentVolume
metadata:
  name: fission-storage
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data
    type: DirectoryOrCreate
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: fission
    name: fission-storage-pvc