{
 "title": "MinIO",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "scrape_jobs",
    "query": {
     "query": "label_values(up{job=~\"data-minio-job-tax|temp-data-minio-job-tax\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Inbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=\"$scrape_jobs\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_total_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_objects_size_distribution{job=~\"$scrape_jobs\"} != 0",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Total Open FDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (minio_node_file_descriptor_open_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Outbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (server,instance) (minio_node_go_routine_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_online_total{job=\"$scrape_jobs\"}",
     "legendFormat": "online"
    },
    {
     "expr": "minio_cluster_nodes_offline_total{job=\"$scrape_jobs\"}",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "Total Disks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_online_total{job=\"$scrape_jobs\"}",
     "legendFormat": "online"
    },
    {
     "expr": "minio_cluster_drive_offline_total{job=\"$scrape_jobs\"}",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "S3 API Data Received Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "S3 API Data Sent Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Scan Activity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minio_usage_last_activity_nano_seconds{job=\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Objects per bucket",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "minio_bucket_usage_object_total{job=\"data-minio-job-tax-buckets\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "minio_bucket_usage_object_total{job=\"temp-data-minio-job-tax-buckets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket size",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_bucket_usage_total_bytes{job=\"data-minio-job-tax-buckets\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "minio_bucket_usage_total_bytes{job=\"temp-data-minio-job-tax-buckets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (\n    # server,\n    api\n) (increase(minio_s3_requests_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "/{{api}} {{server}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (\n    # server,\n    api\n) (increase(minio_s3_requests_errors_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "/{{api}} {{server}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (\n    # server,\n    api\n) (increase(minio_s3_requests_4xx_errors_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "/{{api}} {{server}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (\n    # server,\n    api\n) (increase(minio_s3_requests_5xx_errors_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "/{{api}} {{server}}"
    }
   ]
  },
  {
   "title": "Health Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_erasure_set_online_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Online Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_read_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Read Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_write_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Write Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_healing_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Healing Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Status"
    }
   ]
  },
  {
   "title": "Healing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_heal_objects_heal_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Objects healed in self-healing: {{server}}"
    },
    {
     "expr": "sum by (instance) (increase(minio_heal_objects_error_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Objects with healing failed since server uptime"
    },
    {
     "expr": "sum by (server) (increase(minio_heal_objects_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Objects scanned in self-healing: {{ server }}"
    }
   ]
  },
  {
   "title": "Time Since Last Heal Activity",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "minio_heal_time_last_activity_nano_seconds{job=\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_directories_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_objects_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Scanned Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_versions_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Bucket Scans Finished",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_finished{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Read, Write I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{server}}]"
    },
    {
     "expr": "- rate(minio_node_io_wchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{server}}]"
    }
   ]
  },
  {
   "title": "Internode Traffic",
   "type": "timeseries",
   "description": "Total number of bytes received and sent among all MinIO server instances",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_inter_node_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Received [{{server}}]"
    },
    {
     "expr": "- rate(minio_inter_node_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "Syscalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "- rate(minio_node_syscall_write_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "KMS Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_kms_uptime{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KMS Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_cluster_kms_request_success{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "KMS Request Success [{{server}}]"
    }
   ]
  },
  {
   "title": "KMS Request 4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_error{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "KMS Request Success [{{server}}]"
    }
   ]
  },
  {
   "title": "KMS Request 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_cluster_kms_request_failure{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "KMS Request Success [{{server}}]"
    }
   ]
  }
 ]
}