---
- name: Copying all files to remote
  hosts: all

  tasks:
    - name: Copy files
      copy:
        src: /root/myfile.txt
        dest: /tmp/

        # ownership
        owner: root
        group: root

        # permissions
        # mode: 0777
        # mode: ugo=rw

        # Backing up before writing new file.
        backup: true
