services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - "32181:2181"
      - "7071:7071"
    environment:
      CLUSTER_ID: 'AsATLSToRraxoh2CYWnW0Q'
      ZOOKEEPER_CLIENT_HOSTNAME: zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-javaagent:/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=7071:/jmx-exporter/zookeeper.yml"

    volumes:
      - /home/harshm/kafka/zookeeper1/data:/var/lib/zookeeper/data
      - /home/harshm/kafka/zookeeper1/log:/var/lib/zookeeper/log
      - ./jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar:/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar
      - ./jmx-exporter/kafka.yml:/jmx-exporter/zookeeper.yml
    networks:
      - kafka-net

  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "9092:9092"
      - "7072:7072"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      CLUSTER_ID: 'AsATLSToRraxoh2CYWnW0Q'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1

      KAFKA_OPTS: "-javaagent:/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=7072:/jmx-exporter/kafka.yml"

    volumes:
      - /home/harshm/kafka/broker1:/var/lib/kafka/data
      - ./jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar:/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar
      - ./jmx-exporter/kafka.yml:/jmx-exporter/kafka.yml
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - "9093:9092"
      - "7073:7073"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      CLUSTER_ID: 'AsATLSToRraxoh2CYWnW0Q'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1

      KAFKA_OPTS: "-javaagent:/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=7073:/jmx-exporter/kafka.yml"

    volumes:
      - /home/harshm/kafka/broker2:/var/lib/kafka/data
      - ./jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar:/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar
      - ./jmx-exporter/kafka.yml:/jmx-exporter/kafka.yml
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "30080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    depends_on:
      - kafka-1
      - kafka-2
      - zookeeper
    networks:
      - kafka-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge