apiVersion: v1
kind: Namespace
metadata:
  name: minio-dev
  labels:
    name: minio-dev

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-dev
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30990
      name: minio-ui

    - name: minio-api
      port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: 30900
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      name: minio
      namespace: minio-dev

    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          env:
            - name: MINIO_ROOT_USER
              value: harsh
            - name: MINIO_ROOT_PASSWORD
              value: panchal12345
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

          volumeMounts:
            - mountPath: /data
              name: local-pv
      volumes:
        - name: local-pv
          persistentVolumeClaim:
            claimName: minio-pvc



---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio
  namespace: minio-dev
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: minio-dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio
  hostPath:
    path: /var/data/minio
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - worker

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: minio
