apiVersion: v1
kind: Pod

metadata:
  name: my-pod

spec:
  containers:
    - name: my-container
      image: nginx

      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: region
            operator: In
            values:
              - us-west