apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: nginx
      name: my-container
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - antarctica-east1
        weight: 1

# Operator      Behavior
# In            The label value is present in the supplied set of strings
# NotIn         The label value is not contained in the supplied set of strings
# Exists        A label with this key exists on the object
# DoesNotExist  No label with this key exists on the object