apiVersion: v1
kind: Pod

metadata:
  name: hostpath-pod

spec:
  containers:
  - name: cont1
    image: nginx
    volumeMounts:
    - mountPath: /host_data
      name: host-data-volume

  volumes:
  - name: host-data-volume
    hostPath:
      path: /data
      type: Directory

# Typically needed for system-level operations,
# which is why it should be used with care since it can potentially expose the entire host filesystem to the pod.