apiVersion: v1
kind: ReplicationController

metadata:
  name: rcontroller-nginx

spec:
  replicas: 3
  selector:
    app: my-nginx-apps

  template: # POD metadata
    metadata:
      name: nginx-pod
      labels:
        app: my-nginx-apps

    spec:
        containers:
          - name: nginx-container
            image: nginx
