apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: pvc-example

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

# The above claim asks for 10Gi of storage, which can only be used by one node at a time (ReadWriteOnce).